### ISSUE TITLE
relayer.Dockerfile should build Hermes and not copy

### ISSUE THREAD

**Issue by s3rj1k** [informalsystems/ibc-rs#965] opened 2021-05-20 14:33 UTC
Manual build steps that are provided by docs https://github.com/informalsystems/ibc-rs/blob/master/ci/README.md
do not mention that for a successful relayer build one would need to build hermes beforehand, as dockerfile simply does COPY.

Preferably relayer.Dockerfile should build hermes binary.

**Comment by greg-szabo** [comment] 2021-05-20 15:07
I'm going to update the doc, there's no need to build even the dockerfile now. There's an official image on Docker Hub under `informalsystems/hermes`.

**Comment by greg-szabo** [comment] 2021-05-20 15:10
I'll update the docs, apparently we need fresh docker-compose files for it too.

**Comment by s3rj1k** [comment] 2021-05-20 15:11
@greg-szabo Preferable keeping steps for manual build from source, for testing and developing

**Comment by greg-szabo** [comment] 2021-05-21 02:22
Yep, that turned out to be easier too. It will build master by default but you can override it as described in the documentation.

**Comment by greg-szabo** [comment] 2021-05-21 02:38
Apparently the e2e testing files are used in CI for end-to-end testing... So, just simply building master is not going to work and I think in CI they were relying on a locally built `hermes`.

The problem is that to be able to use the local files to build hermes in docker, the folder containing the local files (`ibc-rs`) needs to be attached to the docker container building the binary. This will have all kinds of interesting side-effects with file permissions after the build finished. (The build happens as root, so all newly created files might end up owned by root, depending on what operating system you use.)

Maybe the CI and the tutorial have to be separated.

@andynog any comments?

**Comment by andynog** [comment] 2021-06-02 11:29
@Greg In the past we had a CI where Hermes was built in the Dockerfile, but since it was used in CI, the build process took very long so they switched to building locally and copying to the container.

**Comment by adizere** [comment] 2021-08-03 08:22
It seems we can close this as the solution side-effects are not clear, and the benefits of copying the container seem to overweigh the costs.

**Closed by adizere** 2021-08-03 08:22 UTC
