### ISSUE TITLE
Timed out packets are not detected by periodic packet clearing feature

### ISSUE THREAD

**Issue by clemensgg** [informalsystems/ibc-rs#2164] opened 2022-05-02 10:14 UTC
## Summary of Bug

If a transaction doesn't reach the mempool, hermes v0.14.0 (with `tx_confirmation = true`) times out while confirming and the packet is dropped (expected behaviour).

```
2022-05-02T09:42:28.265179Z ERROR ThreadId(154) packet{src_chain=osmosis-1 src_port=transfer src_channel=channel-0 dst_chain=cosmoshub-4}: timed out while confirming TxHashes: count=1; D0FFC67F92E9313DFA8A74DC8E5E343943ABB6C5900A682D2E440AC0E12DE265
```

These packets are then not cleared by the `periodic packet clearing feature`; only manual transactions or a hermes restart (with `clear_on_start = true`) are able to process the stuck packets.

This is not a big problem as long the specific path is served by redundant relayers (packets will be picked up by another relayer), but if there is only one relayer the packets will stay undetected until restarting the service or with manual transactions.

## Version

`hermes v0.14.0`

## Steps to Reproduce

It is not clear how to reproduce the initial bug (transaction doesn't reach mempool) but it has been tracked in [issue 1792](https://github.com/informalsystems/ibc-rs/issues/1792).

A fix was included in `v0.14.0` ([issue 1951](https://github.com/informalsystems/ibc-rs/pull/1951)) leading to this new bug, where some packets will stay undetected as described above.

config.toml:
```
# Specify the packets mode.
[mode.packets]

# Whether or not to enable the packet workers. [Required]
enabled = true

# Parametrize the periodic packet clearing feature.
# Interval (in number of blocks) at which pending packets
# should be eagerly cleared. A value of '0' will disable
# periodic packet clearing. [Default: 100]
clear_interval = 150

# Whether or not to clear packets on start. [Default: false]
clear_on_start = true

# Toggle the transaction confirmation mechanism.
# The tx confirmation mechanism periodically queries the `/tx_search` RPC
# endpoint to check that previously-submitted transactions
# (to any chain in this config file) have delivered successfully.
# Experimental feature. Affects telemetry if set to false.
# [Default: true]
tx_confirmation = true
```

## Acceptance Criteria

Timed out transactions will not get stuck in production without a hermes restart / can be processed by the `periodic packet clearing feature`.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment] 2022-05-12 10:11
Marked as blocked until we gather more data/logs/evidence to be able to understand & reproduce the issue.

**Comment by adizere** [comment] 2022-07-26 14:49
Possibly related or duplicate of #2445. Closing this one as we were unable to reproduce or confirm it. We'll reopen if new findings come in.

**Closed by adizere** 2022-07-26 14:49 UTC
Labels: bug, relayer, blocked
