### ISSUE TITLE
Hermes always uses `max_gas` for transactions

### ISSUE THREAD

**Issue by Galadrin** [informalsystems/ibc-rs#1354] opened 2021-09-15 05:19 UTC
## Crate

Hermes ibc_relayer v0.7.1

## Summary of Bug

Hermes transaction always use max_gas amount.

https://www.mintscan.io/osmosis/txs/E742F9EFE2E97A5FCD71FDB3CCDF2FF02BEE47DE5B2D0A51110805736F67C0E4

## Version

v0.7.1

## Acceptance Criteria

Hermes use automatic gas adjustment and `gas_adjustment` from config

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by adizere** [comment] 2021-09-15 08:22
Can you explain in a bit more detail the problem?

Was Hermes configured with `max_gas` 60,000,000 (or thereabout)? It would be good if you can share the gas-related configuration details from config.toml for chain Osmosis.

Note that Hermes will by default try to simulate each tx, thus obtaining an approximate amount of gas it should use, and thenit will subsequently submit the transaction with that approximated amount (the amount is adjusted up using `gas_adjustment`). If the tx simulation fails, then Hermes will simply use the configured `max_gas`.

https://github.com/informalsystems/ibc-rs/blob/5d38857ac41affd93573c100fedf333b979dfcf3/relayer/src/chain/cosmos.rs#L335-L343

**Comment by Galadrin** [comment] 2021-09-15 10:31
Hi,
my config is the same as issue 1342

https://github.com/informalsystems/ibc-rs/issues/1342#issuecomment-918590572

for Osmosis, Crypto.org and Cosmos, the max_gas value is used for every transaction.
the transaction shared is an example.

**Comment by hu55a1n1** [comment] 2021-09-16 12:22
Hi @Galadrin! It appears that you have configured `gas_adjustment=5` for the `osmosis-1` chain in your [config.toml](https://pastebin.com/Pbca30tz). And that probably caused `hermes` to use the `max_gas` based on this calculation ->
https://github.com/informalsystems/ibc-rs/blob/5d38857ac41affd93573c100fedf333b979dfcf3/relayer/src/chain/cosmos.rs#L405-L410

Can you try a `gas_adjustment < 1` i.e. `0.5`?

**Comment by Galadrin** [comment] 2021-09-16 19:12
I have the same symptom on Crypto.org and Cosmos chain.
and the issue is not present using v0.7.0

**Comment by Galadrin** [comment] 2021-09-18 07:44
here is 2 transaction on Cosmos and Crypto.org

I've limited the max_gas on cosmos to not drain the wallet by $200 per days.

https://www.mintscan.io/cosmos/txs/D5C5701811BD5639E892FDE9AA382762B66BC6AA3D149AD621D14EBAF8B9E8E4

https://www.mintscan.io/crypto-org/txs/32C43358FAF5A36F1748F4114CDF105544958EBA5D72163FA07F500400E0906F

**Comment by hu55a1n1** [comment] 2021-09-21 09:49
Are you still seeing this problem? And did you get a chance to try my previous suggestion for `gas_adjustment`?

**Comment by Galadrin** [comment] 2021-09-21 22:55
> Are you still seeing this problem? And did you get a chance to try my previous suggestion for `gas_adjustment`?

Hi,
Yes, still have the issue.
I tested with 0.5 then 0.1 for `gas_adjustment` with same result.
then remove the parameter, always with same result.

**Comment by romac** [comment] 2021-09-22 12:28
@Galadrin Do you have any Hermes logs (preferably with `log_level = "trace"`) that you could share with us?

**Comment by Galadrin** [comment] 2021-09-22 20:15
@romac please find attached the hermes logs after restart with `log_level = "trace"`.
I've check and some TX have been made.
[hermes.log](https://github.com/informalsystems/ibc-rs/files/7213500/hermes.log)

**Comment by mircea-c** [comment] 2021-09-23 15:40
Here's an example I would like to understand.

The hermes config for this chain is:
```
gas_price = { price = 0.001, denom = 'uosmo' }
max_gas=1000000
```

The resulting transaction:
```
Gas (used / wanted)
453,860 / 1,000,000
```

If I undestand this correctly, the fee paid should be `0.00045OSMO`

Instead, the actual fee is `Fee 0.001000OSMO`

https://www.mintscan.io/osmosis/txs/85C390DDE1A501A4512BF7F62C0CE2113C9ED0C0A480124183AA7FCA28DB784E

**Comment by Galadrin** [comment] 2021-09-23 21:55
Hi @mircea-c, I'm not totally agree :

on Osmosis chain, my gas fee settings are :
```
gas_price = { price = 0.000, denom = 'uosmo' }
max_gas = 60000000
```

on Cosmos chain :
```
gas_price = { price = 0.001, denom = 'uatom' }
max_gas = 1000000
```
https://www.mintscan.io/cosmos/txs/E7BAAC35019236CF1D52276C40EAF36326A07C587EBF7719A2FE7BF9762B6672

on Crypto.org chain :
```
gas_price = { price = 0.025, denom = 'basecro' }
max_gas = 8000000
```
https://www.mintscan.io/crypto-org/txs/F1C70D57A9FF5028DDBF6E39789AD3206DE14B9F4A29E82E6A047521BFC3D83A

**Comment by adizere** [comment] 2021-09-29 08:53
> Here's an example I would like to understand.
> 
> The hermes config for this chain is:
> 
> ```
> gas_price = { price = 0.001, denom = 'uosmo' }
> max_gas=1000000
> ```
> 
> The resulting transaction:
> 
> ```
> Gas (used / wanted)
> 453,860 / 1,000,000
> ```


I think Hermes submitted this transaction specifying that it allocates `1,000,000` gas, so that's how much was spent from the relayer wallet. The chain/execution module only required `453,860` only in fact. In this example, Hermes submitted the tx specifying `1,000,000` gas because of one of two reasons:

1. Hermes did a /simulate and found out that the chain estimates it will take 1 million gas for that specific tx, so Hermes will use that exact amount (adjusted with [`gas_adjustment`](https://github.com/informalsystems/ibc-rs/blob/79210ec95f40ecb7aabcc5691c5d3a07ffbef280/config.toml#L129)) or
2. Hermes was unsuccessful in doing the /simulate for that tx, and so it used the predefined `max_gas` from `config.toml` for that chain.

The first option is unlikely. The second one is more likely. Searching the Hermes logs for tx hash `85C390DDE1A501A4512BF7F62C0CE2113C9ED0C0A480124183AA7FCA28DB784E` could probably reveal what is the cause for unsuccesful tx /simulate.

----


> @romac please find attached the hermes logs after restart with `log_level = "trace"`.
> I've check and some TX have been made.
> [hermes.log](https://github.com/informalsystems/ibc-rs/files/7213500/hermes.log)

This is a good first step, thank you @Galadrin ! The relevant lines of log are as follows:


```
$ cat hermes.log | grep 'estimated'
Sep 22 20:07:02 Beast hermes[28217]: Sep 22 20:07:02.542 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
Sep 22 20:07:21 Beast hermes[28217]: Sep 22 20:07:21.557 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
Sep 22 20:07:42 Beast hermes[28217]: Sep 22 20:07:42.523 TRACE [cosmoshub-4] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uatom", amount: "1000" }], gas_limit: 1000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uatom", amount: "1000" }], gas_limit: 1000000, payer: "", granter: "" }
Sep 22 20:08:02 Beast hermes[28217]: Sep 22 20:08:02.466 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
Sep 22 20:08:56 Beast hermes[28217]: Sep 22 20:08:56.123 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
Sep 22 20:09:15 Beast hermes[28217]: Sep 22 20:09:15.281 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
Sep 22 20:09:48 Beast hermes[28217]: Sep 22 20:09:48.881 TRACE [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 60000000, payer: "", granter: "" }
```

Normally, the fee should be adjusted __down__, to smaller amounts. But it seems to remain unchanged. Most likely the /simulate fails. We will do some debugging locally and come back to you. Would you be open to running Hermes build from a `master` or a developer branch?

**Comment by ancazamfir** [comment] 2021-09-29 14:05
There is also this case as described in the code comments. 
```
        // Try to simulate the Tx.
        // It is possible that a batch of messages are fragmented by the caller (`send_msgs`) such that
        // they do not individually verify. For example for the following batch
        // [`MsgUpdateClient`, `MsgRecvPacket`, ..., `MsgRecvPacket`]
        // if the batch is split in two TX-es, the second one will fail the simulation in `deliverTx` check
        // In this case we just leave the gas un-adjusted, i.e. use `self.max_gas()`
```

**Comment by Sdpierret** [comment] 2021-09-29 21:16
> Would you be open to running Hermes build from a `master` or a developer branch?

Yes, we can run engineering build if needed. it can't be worst than today ;)

**Comment by Galadrin** [comment] 2021-09-29 21:39
Hi,
> Would you be open to running Hermes build from a master or a developer branch?

Yes, we can run custom build if needed for test.

**Comment by romac** [comment] 2021-09-30 16:41
@Galadrin @mdyring So that's indeed a regression introduced in Hermes v0.7.0 which only occurs with chains based on Cosmos SDK 0.42. Indeed, when doing the compatibility upgrade for SDK 0.43, we introduced a backward-incompatible change which broke the tx simulation on 0.42.

We have a fix for this in #1405 if you want to run a custom build of Hermes and see if it does indeed fix the problem for you. If you enable `log_level = "debug"` you should see the fee being adjusted properly, eg.

```
Sep 30 18:37:58.791 DEBUG ThreadId(29) [ibc-1] send_tx: sending 2 messages using account sequence 5
Sep 30 18:37:58.811 DEBUG ThreadId(29) [ibc-1] default fee: Fee { amount: "900000stake", gas_limit: 900000000 }
Sep 30 18:37:58.836 DEBUG ThreadId(29) [ibc-1] simulated gas: Ok(Some(GasInfo { gas_wanted: 0, gas_used: 117532 }))
Sep 30 18:37:58.836 TRACE ThreadId(29) [ibc-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: "900000stake", gas_limit: 900000000 } to Fee { amount: "130stake", gas_limit: 129286 }
```

**Comment by Galadrin** [comment] 2021-09-30 21:51
Hi @romac 

here is the steps I follow :
`$ cd hermes-sources/`
`$ git fetch --all`
`$ git checkout origin/romac/fee-simulate-0.42`
`$ cargo install ibc-relayer-cli --bin hermes --locked --force`

then restart with TRACE log level
I don't find the log about `default fee` and `simulate gas`

```
Sep 30 21:42:36.688 DEBUG ThreadId(50) [osmosis-1] send_tx: sending 2 messages using nonce 72346
Sep 30 21:42:36.689 TRACE ThreadId(50) [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 2000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uosmo", amount: "0" }], gas_limit: 2000000, payer: "", granter: "" }
Sep 30 21:42:36.696 DEBUG ThreadId(50) [osmosis-1] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(86C593B187E78F8574F65C52E4F902CC7B30E68457CFA18402C67A924B52B658) }
Sep 30 21:42:36.696  INFO ThreadId(16487) [Async~>osmosis-1] response(s): 1; Ok:86C593B187E78F8574F65C52E4F902CC7B30E68457CFA18402C67A924B52B658
Sep 30 21:42:36.696  INFO ThreadId(16487) [cosmoshub-4:transfer/channel-141 -> osmosis-1] success
```

```
Sep 30 21:43:05.418 DEBUG ThreadId(52) send_messages_and_wait_check_tx with 2 messages
Sep 30 21:43:05.418 DEBUG ThreadId(52) [cosmoshub-4] send_tx: sending 2 messages using nonce 54019
Sep 30 21:43:05.422 TRACE ThreadId(52) [cosmoshub-4] send_tx: based on the estimated gas, adjusting fee from Fee { amount: [Coin { denom: "uatom", amount: "100" }], gas_limit: 1000000, payer: "", granter: "" } to Fee { amount: [Coin { denom: "uatom", amount: "100" }], gas_limit: 1000000, payer: "", granter: "" }
Sep 30 21:43:05.425 DEBUG ThreadId(52) [cosmoshub-4] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(914A80786F2D90F6CE018898D376BF2C25985AB7BC4FA677B4B924B661AA7329) }
Sep 30 21:43:05.425  INFO ThreadId(15710) [Async~>cosmoshub-4] response(s): 1; Ok:914A80786F2D90F6CE018898D376BF2C25985AB7BC4FA677B4B924B661AA7329
Sep 30 21:43:05.425  INFO ThreadId(15710) [osmosis-1:transfer/channel-0 -> cosmoshub-4] success
```

**Comment by romac** [comment] 2021-09-30 22:00
That's really weird. Can you please check that the code in `cosmos.rs` that you checked out matches the code in the PR? Can you also please post the output of `hermes version`? Assuming that's the executable you are running.

Or otherwise run it with `cargo run -- start`?

I just double checked the code in the PR and it should match the output I just posted above. If that doesn't work maybe we can have a synchronous debug session together sometime next week if that works for you? cc @adizere

**Comment by romac** [comment] 2021-09-30 22:03
Nevermind, try installing Hermes with

```
cargo install --path relayer-cli 
```

The command you used above installed the version that's on crates.io, not the one from the branch.

Alternatively, just do a `cargo build` and then invoke Hermes with `./target/debug/hermes`

**Comment by Galadrin** [comment] 2021-09-30 22:06
> That's really weird. Can you please check that the code in `cosmos.rs` that you checked out matches the code in the PR? 
Yes the code match

> Can you also please post the output of `hermes version`? Assuming that's the executable you are running.
```$ .cargo/bin/hermes version
Sep 30 22:04:45.600  INFO ThreadId(01) using default configuration from '/srv/hermes/.hermes/config.toml'
hermes 0.7.2
```

**Comment by Galadrin** [comment] 2021-09-30 22:23
> The command you used above installed the version that's on crates.io, not the one from the branch.

OK :) sorry

this time `hermes version` return `hermes 0.7.2+11bea3da`

Look like the modification works :

https://www.mintscan.io/cosmos/txs/06DD939153010C79FCE1C395A222F5A8DCF58150DD5AB867C74EFF05AC59E32C
https://www.mintscan.io/osmosis/txs/65E1A765970312E10A35F3DAE69A26B9F7BE8BB60455BA5A479D5510CE5F1344

```
Sep 30 22:22:34.468 DEBUG ThreadId(50) [osmosis-1] send_tx: sending 2 messages using account sequence 72390
Sep 30 22:22:34.468 DEBUG ThreadId(50) [osmosis-1] default fee: Fee { amount: "0uosmo", gas_limit: 2000000 }
Sep 30 22:22:34.484 DEBUG ThreadId(50) [osmosis-1] simulated gas: Ok(Some(GasInfo { gas_wanted: 0, gas_used: 413782 }))
Sep 30 22:22:34.484 TRACE ThreadId(50) [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: "0uosmo", gas_limit: 2000000 } to Fee { amount: "0uosmo", gas_limit: 455161 }
Sep 30 22:22:34.489 DEBUG ThreadId(50) [osmosis-1] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(A2CB73AD59723BF0A3CC63E15B4953983647C915120C8908BC07294E6A95BED6) }
Sep 30 22:22:34.489  INFO ThreadId(7414) [Async~>osmosis-1] response(s): 1; Ok:A2CB73AD59723BF0A3CC63E15B4953983647C915120C8908BC07294E6A95BED6
```

**Comment by adizere** [comment] 2021-10-01 07:51
> this time `hermes version` return `hermes 0.7.2+11bea3da`
> 
> Look like the modification works :
> 
> https://www.mintscan.io/cosmos/txs/06DD939153010C79FCE1C395A222F5A8DCF58150DD5AB867C74EFF05AC59E32C https://www.mintscan.io/osmosis/txs/65E1A765970312E10A35F3DAE69A26B9F7BE8BB60455BA5A479D5510CE5F1344
> 
> ```
> Sep 30 22:22:34.468 DEBUG ThreadId(50) [osmosis-1] send_tx: sending 2 messages using account sequence 72390
> Sep 30 22:22:34.468 DEBUG ThreadId(50) [osmosis-1] default fee: Fee { amount: "0uosmo", gas_limit: 2000000 }
> Sep 30 22:22:34.484 DEBUG ThreadId(50) [osmosis-1] simulated gas: Ok(Some(GasInfo { gas_wanted: 0, gas_used: 413782 }))
> Sep 30 22:22:34.484 TRACE ThreadId(50) [osmosis-1] send_tx: based on the estimated gas, adjusting fee from Fee { amount: "0uosmo", gas_limit: 2000000 } to Fee { amount: "0uosmo", gas_limit: 455161 }
> Sep 30 22:22:34.489 DEBUG ThreadId(50) [osmosis-1] send_tx: broadcast_tx_sync: Response { code: Ok, data: Data([]), log: Log("[]"), hash: transaction::Hash(A2CB73AD59723BF0A3CC63E15B4953983647C915120C8908BC07294E6A95BED6) }
> Sep 30 22:22:34.489  INFO ThreadId(7414) [Async~>osmosis-1] response(s): 1; Ok:A2CB73AD59723BF0A3CC63E15B4953983647C915120C8908BC07294E6A95BED6
> ```

Many thanks @Galadrin for reporting the problem, and your patience with helping debug this, it was a tricky one having to do with SDK version compatibilities!

We aim to cut a new release today (Oct 1) with the fix.

**Closed** 2021-10-04 16:49 UTC
Labels: question, relayer, user experience (UX)
