### ISSUE TITLE
Hermes feature: Relay ics20/27 packets after successful governance proposal 

### ISSUE THREAD

**Issue by seantking** [informalsystems/ibc-rs#1093] opened 2021-06-16 12:40 UTC
## Crate

`relayer` 

## Summary

At present, the Hermes relayer seems to not pick up IBC packets that need to be relayed in the event of a successful governance proposal passing. For example, if a governance proposal handler triggers an ics20 transfer, the Hermes relayer should listen for this and relay the packet. 

I am working on a client flow for interchain accounts that involves creating/passing governance proposals to control an account (so sending packets on an ics27 channel). Experimental example (ics20 transfer on successful governance proposal passing)[here](https://github.com/cosmos/interchain-accounts/commit/6bc7cb6654cbb19b33516882ddd18f8dceb0ed20#diff-7bae92f8fad787dc805142fdd9232746b842233cff20c12b9d1b69e217b5e668R60) 

I see that [here](https://github.com/informalsystems/ibc-rs/blob/master/relayer/src/event/rpc.rs#L102) the Hermes relayer seems to only be listening for specific module "actions". I don't fully understand this pattern, is this intentionally part of the Hermes design? In the case of interchain accounts, there will be many custom events that will need to be added here as each user of interchain accounts will need to define their own custom functionality. I think this is not sustainable as in this case each chain will need to fork their own version of Hermes. 

## Problem Definition

`What problems may be addressed by introducing this feature?`

Governance is a feature that should be supported I think. 

## Proposal

When a governance proposal passes, if the proposal handler creates an IBC packet to send to another chain, the relayer should listen for this and relay the packet successfully.

## Acceptance Criteria

Same as above.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment] 2021-06-16 12:47
Sounds like event listening for begin blocker and end blocker aren't getting picked up by hermes? Would be great to support all IBC events emitted in begin blocker/end blocker (even those not caused by a governance proposal)

**Comment by ancazamfir** [comment] 2021-06-17 15:10
> Sounds like event listening for begin blocker and end blocker aren't getting picked up by hermes? Would be great to support all IBC events emitted in begin blocker/end blocker (even those not caused by a governance proposal)

Indeed hermes doesn't pick these up. Will look into it. Do you have a dump of a block that contains some events in begin/end block? Or a block height on cosmoshub-4 that I can take as example?

**Comment by ancazamfir** [comment] 2021-06-17 15:43
@seantking can you provide some steps to reproduce this issue? I can use some sdk branch and build gaia from there, etc. just need a bit more detail

**Comment by colin-axner** [comment] 2021-06-17 15:56
> Indeed hermes doesn't pick these up. Will look into it. Do you have a dump of a block that contains some events in begin/end block? Or a block height on cosmoshub-4 that I can take as example for testing?

Unfortunately I don't. There should be some event every block for a begin or end blocker. Looks like minting will mint the inflation [amount every block](https://github.com/cosmos/cosmos-sdk/blob/0e64fa77d1173b485421e0dd4d4e95af462cef96/x/mint/abci.go#L46)

**Comment by adizere** [comment] 2021-09-06 14:45
Should be fixed by #1172.

**Closed by adizere** 2021-09-06 14:45 UTC
