### ISSUE TITLE
The IBC `ibc` crate should be `no-std`

### ISSUE THREAD

**Issue by zmanian** [informalsystems/ibc-rs#29] opened 2020-03-11 17:08 UTC
# Summary

The `relayer-modules` crate should be `no-std`.

## Problem Definition

The `relayer-modules` crate should support `no-std` this would make it more useful for solo nodes running in embedded environments and integrating deployment in wasm environments like Substrate Pallets and Eth2 Execution Environments.

## Proposal

Ideally the full relayer can be in `std` environment and use crates like tokio. 

There is progress in support unclear how this interacts with using core::future in the API. Needs more inverstigation.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by hxrts** [comment] 2021-01-06 15:19
The cdot team raised this same issue as Substrate uses no-std.

**Comment by adizere** [comment] 2021-01-07 13:32
We'd like to understand the priority for this issue. Suppose we adapt the `modules` crate to no-std in the second trimester of 2021 (after may, before end of august), would that work?

**Comment by hxrts** [comment] 2021-01-07 15:02
@en @livelybug @toliuyi maybe you can comment on whether this is blocking, or a feature that's nice-to-have?

**Comment by en** [comment] 2021-01-08 07:41
Sorry, I submitted a duplicate issue( #508 ) today because I missed the notification.

**Comment by andynog** [comment] 2021-03-08 18:41
the no_std support on `tendermint-rs` repo -> https://github.com/informalsystems/tendermint-rs/issues/824

**Comment by adizere** [comment] 2022-01-06 14:24
#1158 thoroughly tracks efforts towards no_std. Closing as duplicate of that.

**Closed by adizere** 2022-01-06 14:24 UTC
Labels: enhancement, substrate-ibc, no-std
