### ISSUE TITLE
Hermes ports not getting detected

### ISSUE THREAD

**Issue by dhogaivannan** [informalsystems/ibc-rs#1861] opened 2022-02-09 12:47 UTC
## Crate

ibc-rs (Hermes)

## Summary of Bug

Creating channels between Band Protocol and another chain from it's `oracle` port for fetching prices, it throws could not resolve channel and port is invalid.

## Version

hermes - release - v0.11.1

## Steps to Reproduce

ibc-0 = Band Protocol (band-laozi-testnet4)
ibc-1 = Any chain with oracle port*

`* = https://github.com/comdex-official/comdex/tree/oracle-liquidation` (This binary and branch contains bandoracle port for fetching prices)

`hermes create channel test-1 band-laozi-testnet4 --port-a bandoracle --port-b oracle`

Logs:
```
WARN ThreadId(01) cannot resolve channel version for unknown port id 'oracle'
Error: channel error: could not resolve channel version because the port is invalid: oracle
```

## Acceptance Criteria

Port from Band or Comdex getting detected for channel creation.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment] 2022-02-09 13:47
Can you please try from this branch and see if it fixes the issue for you? https://github.com/informalsystems/ibc-rs/pull/1825

**Comment by romac** [comment] 2022-02-09 13:48
Likely duplicate of https://github.com/informalsystems/ibc-rs/issues/1837

**Comment by romac** [comment] 2022-02-14 09:27
@dhogaivannan I am working on this in #1825

**Comment by litvintech** [comment] 2022-02-15 10:18
I'm confirming this issue on 0.11.1, 0.9.0 works fine

**Comment by romac** [comment] 2022-02-15 12:46
@dhogaivannan Can you please try with Hermes v0.11.1 by specifying the appropriate version using the `--channel-version` parameter of the `hermes create channel` command?

**Comment by romac** [comment] 2022-02-15 12:47
@litvintech Thanks for the heads-up! I have a few follow-up questions:

a) Are you using the `--channel-version` option?
b) Can you please paste the commands you are running on 0.11.1 and 0.9.0?
c) Does it work with 0.10.0?

**Comment by dhogaivannan** [comment] 2022-02-16 05:55
> 

@romac , yes sure, v0.11.1 official build or the branch 1797-ibc-v3? I'll go ahead with official branch for now and get back to you

**Comment by dhogaivannan** [comment] 2022-02-16 13:58
@romac , tried #1882 , threw the same error, channel version for unknown port id 'oracle', let me know if i tried it too early

**Comment by romac** [comment] 2022-02-16 15:01
Did you specify the version with `--channel-version`?

**Comment by romac** [comment] 2022-02-16 16:39
Can you please post the full command and output?

**Comment by dhogaivannan** [comment] 2022-02-16 20:12
Yes sure, ran this command:
`hermes create channel band-laozi-testnet4 test-1 --port-a oracle --port-b bandoracle --channel-version bandchain-1`

Output after connection-handshake is finished (CLient and connections are done)

`2022-02-16T13:55:16.066381Z  WARN ThreadId(01) cannot resolve channel version for unknown port id 'oracle'`
and repeats in a loop

**Comment by romac** [comment] 2022-02-17 12:24
The branch you are running might be outdated because that warning is no longer present in the branch `romac/1861-non-standard-ports`, can you please try to do a `git pull` and also set `log_level = "trace"` in the Hermes configuration file?

**Comment by romac** [comment] 2022-02-17 13:58
@dhogaivannan I think I have a proper fix for this issue, and will notify you when you can test again with the `romac/1861-non-standard-ports` branch.

**Comment by dhogaivannan** [comment] 2022-02-17 15:06
@romac , the latest pull from your branch works fine, thanks a lot for your help!

**Closed** 2022-02-17 19:13 UTC
Labels: P-high, duplicate, in progress

**Comment by dhogaivannan** [comment] 2022-02-18 05:05
> @romac , while clearing packets with  `hermes tx raw packet-recv band-laozi-testnet4 test-1 bandoracle channel-0`, it threw this error 

```
failed to simulate tx. propagating error to caller: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet callback failed: cannot unmarshal packet data: proto: illegal wireType 6: unknown request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "10634"} }
Error: link error: failed with underlying error: gRPC call failed with status: status: Unknown, message: "failed to execute message; message index: 1: timeout packet callback failed: cannot unmarshal packet data: proto: illegal wireType 6: unknown request", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "10634"} }
```

**Comment by romac** [comment] 2022-02-18 09:00
@dhogaivannan This does not seem to have anything to do with this issue. Can you please gather as much information as you can (trace logs, Hermes version, etc.) and open a new issue?
