### ISSUE TITLE
Create client fails with GRPC error against chains using Cosmos SDK 0.42.3

### ISSUE THREAD

**Issue by andynog** [informalsystems/ibc-rs#789] opened 2021-03-30 21:58 UTC
## Crate

ibc-relayer

## Summary of Bug

Greg and Mircea were doing some tests with testnets and Hermes and when issuing a `create client` command they get an error.

## Version

master

## Steps to Reproduce

Configure two chains that use Cosmos SDK v0.42.3

When running `create client` the error shows up:

```
hermes -c config.toml create client stargate-final nyancat-8
{"status":"error","result":"tx error: error raised while creating client: failed while building client state from src chain (nyancat-8) with error: GRPC error: status: Unimplemented, message: \"unknown service cosmos.staking.v1beta1.Query\", details: [], metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\"} }"}
```

We might need to update our protos to v0.42.3 (currently at v0.42.1)

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ancazamfir** [comment] 2021-03-31 10:32
> Configure two chains that use Cosmos SDK v0.42.3

We need more details as I cannot reproduce. How were the chains configured exactly? I did test with `gaia v4.2.0` that is using `cosmos-sdk v0.42.3` and all tests pass without protobuf upgrade. And have been using this setup since gaia release was out.
 
Have you also tried the reverse `hermes -c config.toml create client nyancat-8 stargate-final`? Same error?

@mircea-c @greg-szabo ?

**Comment by andynog** [comment] 2021-03-31 13:23
> > Configure two chains that use Cosmos SDK v0.42.3
> 
> We need more details as I cannot reproduce the error. How were the chains configured exactly? I did test with `gaia v4.2.0` that is using `cosmos-sdk v0.42.3` and all tests pass without protobuf upgrade. And have been using this setup since gaia release was out.
> 
> Have you also tried the reverse `hermes -c config.toml create client nyancat-8 stargate-final`? Same error?
> 
> @mircea-c @greg-szabo ?

doing the reverse gives out the same error message

**Comment by mircea-c** [comment] 2021-03-31 14:27
> How were the chains configured exactly?

We did not do any configuration for these chains as they are public testnets run by others. We did confirm they are using SDK v0.42.3. Any genesis parameters that we should look for?

**Comment by ancazamfir** [comment] 2021-03-31 22:03
Are these build in Go? Open source? Can we check the `go.mod` and config files? Can we clone the code and debug by starting a testnet ourselves?
That error comes from the relayer `CosmosSDK` implementation of `build_client_state()` that happens when a client is created. This function performs a gRPC query for the unbonding period which is implemented by the staking module.
Do other queries work, e.g. `hermes query clients nyancat-8`?

**Comment by andynog** [comment] 2021-04-01 19:51
> Do other queries work, e.g. `hermes query clients nyancat-8`?

the `query clients` command gives out the same GRPC error above

But I can query the client state using `hermes query client state nyancat-8 07-tendermint-0`

```
{“status”:“success”,“result”:{“allow_update_after_expiry”:true,“allow_update_after_misbehaviour”:true,“chain_id”:“cosmoshub-4”,“frozen_height”:{“revision_height”:0,“revision_number”:0},“latest_height”:{“revision_height”:5672485,“revision_number”:4},“max_clock_drift”:{“nanos”:0,“secs”:600},“trust_level”:{“denominator”:“3”,“numerator”:“1”},“trusting_period”:{“nanos”:0,“secs”:1209600},“unbonding_period”:{“nanos”:0,“secs”:1814400},“upgrade_path”:[“upgrade”,“upgradedIBCState”]}}
```

**Comment by ancazamfir** [comment] 2021-04-02 06:22
> the query clients command gives out the same GRPC error above

it's still `unknown service cosmos.staking.v1beta1.Query`?

Can I have access to the setup and `config.toml`?

**Comment by ancazamfir** [comment] 2021-04-02 06:47
Also, what is the output of `grpcurl -plaintext <host>:<grpc_port> list`?

**Comment by mircea-c** [comment] 2021-04-06 12:38
Hi @ancazamfir! 
The code for `stargate-final` comes from [https://github.com/cosmos/gaia/tree/v4.2.0](gaiad) (4.2.0 tag)
Nyancat is run by [https://github.com/irisnet/irishub/tree/v1.0.1](irishub), although it seems that the error is not coming from there.

Here are the toml files that are used
[nyancat-8.txt](https://github.com/informalsystems/ibc-rs/files/6264642/nyancat-8.txt)
[stargate-final.txt](https://github.com/informalsystems/ibc-rs/files/6264643/stargate-final.txt)

**Comment by andynog** [comment] 2021-04-06 21:45
> Also, what is the output of `grpcurl -plaintext <host>:<grpc_port> list`?

If I grpcurl the stargate-final server I get an error:

```
Failed to list services: server does not support the reflection API
```

But if I query another full node that is running on cosmoshub-4 (same sdk v0.42.3) I get the list of services

```
cosmos.auth.v1beta1.Query
cosmos.bank.v1beta1.Query
cosmos.base.reflection.v1beta1.ReflectionService
cosmos.base.tendermint.v1beta1.Service
cosmos.distribution.v1beta1.Query
cosmos.evidence.v1beta1.Query
cosmos.gov.v1beta1.Query
cosmos.mint.v1beta1.Query
cosmos.params.v1beta1.Query
cosmos.slashing.v1beta1.Query
cosmos.staking.v1beta1.Query
cosmos.tx.v1beta1.Service
cosmos.upgrade.v1beta1.Query
grpc.reflection.v1alpha.ServerReflection
ibc.applications.transfer.v1.Query
ibc.core.channel.v1.Query
ibc.core.client.v1.Query
ibc.core.connection.v1.Query
```

Also if I query the `/node_info` REST endpoint for each server all the `build_deps` are equal but some properties in the `application_version` differs (mostly the version and commit)

stargate-final
```
    "application_version": {
        "name": "gaia",
        "server_name": "gaiad",
        "version": "-",
        "commit": "",
        "build_tags": "netgo ledger,",
        "go": "go version go1.15.10 linux/amd64",
```

Full node (gaiad v4.2.0)

```
  "application_version": {
        "name": "gaia",
        "server_name": "gaiad",
        "version": "v4.2.0",
        "commit": "535be14a8bdbfeb0d950914b5baa2dc72c6b081c",
        "build_tags": "netgo,ledger",
        "go": "go version go1.15.2 linux/amd64",
```

this might not matter, might just be a build configuration but just something different

**Comment by andynog** [comment] 2021-05-27 17:42
Hi @mircea-c, would you be able to confirm if this is still an issue ? I remember that some of the issues might have been caused by the fact that the gaiad docker image was not the same as the gaiad release binary ? Could you please confirm if you're still testing this and if we should close this or not. Thanks!

**Comment by adizere** [comment] 2021-08-10 12:07
Closing as we cannot reproduce this anymore.

**Closed by adizere** 2021-08-10 12:07 UTC
Labels: bug
